.idea/gradle.xml
.idea/kotlinc.xml
.idea/misc.xml
app/build.gradle
app/google-services.json
build.gradle

FEAT : 파이어베이스 연동

---

.idea/kotlinc.xml
.idea/misc.xml
app/build.gradle
app/google-services.json
app/src/main/AndroidManifest.xml
app/src/main/res/layout/sign_up_page.xml
app/src/main/res/layout/start_page.xml
build.gradle

FEAT: sign_up, login layout Add 

---

.idea/misc.xml
app/build.gradle

FEAT : gradle 요소 추가

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/ccoli_market/LoginActivity.kt
app/src/main/java/com/example/ccoli_market/MainActivity.kt
app/src/main/java/com/example/ccoli_market/SignUpActivity.kt
app/src/main/res/layout/activity_main.xml

회원가입구현했습니다.
SignUpActivity.kt 추가했습니다.

FEAT: 파이어베이스 회원가입 구현

---

app/src/main/java/com/example/ccoli_market/SignUpActivity.kt
app/src/main/res/layout/sign_up_page.xml

평가표에 맞춰 요소 추가
회원가입 창에서 성함과, 생년월일 텍스트 창 생성

FEAT: 회원가입

---

.idea/misc.xml
build.gradle

BLD: build.gradle 수정

---

.idea/misc.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/ccoli_market/ChatActivity.kt
app/src/main/java/com/example/ccoli_market/DetailActivity.kt
app/src/main/java/com/example/ccoli_market/MainActivity.kt
app/src/main/java/com/example/ccoli_market/SignUpActivity.kt
app/src/main/res/drawable/previous.xml
app/src/main/res/layout/chat_layout.xml

채팅기능을 구현하기 위한 레이아웃과 코틀린 파일을 생성하였습니다

FEAT: chat_layout, ChatActivity 생성

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/ccoli_market/AddItemActivity.kt
app/src/main/java/com/example/ccoli_market/LoginActivity.kt
app/src/main/java/com/example/ccoli_market/MainActivity.kt
app/src/main/java/com/example/ccoli_market/Model.kt
app/src/main/res/drawable/ic_camera.xml
app/src/main/res/layout/add_item.xml
app/src/main/res/values/colors.xml

add_item.xml에 상품 등록 페이지를 만들었고 AddItemActivity에 앨범에서 사진을 불러오는 코드를 구현하였습니다.

FEAT: 상품 등록 페이지 생성

---

.idea/misc.xml
app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/ccoli_market/AddItemFragment.kt
app/src/main/java/com/example/ccoli_market/MainActivity.kt
app/src/main/java/com/example/ccoli_market/Product_list.kt
app/src/main/res/menu/bottom_navigation_view.xml

bottombar에 AddItemFragment추가했습니다.
AddItemActivity->AddItemFragment

FEAT: 프래그먼트로 변환 및 bottombar연결

---

.idea/misc.xml
app/src/main/java/com/example/ccoli_market/Product_list.kt
app/src/main/res/drawable/additem.xml
app/src/main/res/drawable/chat_icon.xml
app/src/main/res/menu/bottom_navigation_view.xml
app/src/main/res/values/strings.xml

리스트 페이지에서 로그아웃 버튼을 누르면 로그인 페이지로 가도록 기능 구현

FEAT: 로그아웃 기능 구현

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/example/ccoli_market/AddItemFragment.kt
app/src/main/java/com/example/ccoli_market/ArticleModel.kt
app/src/main/res/layout/activity_detail.xml
app/src/main/res/layout/add_item.xml

FEAT: Add_item 아이템 추가

---

app/src/main/AndroidManifest.xml
app/src/main/res/menu/bottom_navigation_view.xml

bottom_navigation에서 add_item부분 삭제하였고, 첫화면을 MainActivity->LoginActivity로 바꾸었습니다.

FEAT: 첫화면 Login page로 변경

---

.idea/misc.xml
app/src/main/java/com/example/ccoli_market/ArticleModel.kt
app/src/main/java/com/example/ccoli_market/DetailActivity.kt
app/src/main/java/com/example/ccoli_market/HomeFragment.kt

FEAT : 판매글목록 - 세부내용 연결

---

app/src/main/res/menu/popup_menu.xml
app/src/main/res/menu/popup_menu2.xml
app/src/main/res/values/strings.xml

FEAT: 수정을 위한 파일 생성

---

app/build.gradle
app/src/main/java/com/example/ccoli_market/DetailActivity.kt
app/src/main/java/com/example/ccoli_market/HomeFragment.kt
app/src/main/res/layout/activity_detail.xml

FEAT : 세부화면 이미지 데이터 전송

---

app/src/main/java/com/example/ccoli_market/DBKey.kt
app/src/main/java/com/example/ccoli_market/MainActivity.kt
app/src/main/java/com/example/ccoli_market/MyPageFragment.kt
app/src/main/java/com/example/ccoli_market/SignUpActivity.kt
app/src/main/java/com/example/ccoli_market/User.kt
app/src/main/res/layout/fragment_mypage.xml
app/src/main/res/layout/sign_up_page.xml

로그인 했을때 fragment_mypage.xml에 이메일 표시되게 하였고, 로그아웃 버튼 누르면 로그인화면으로 이동하게 하였습니다. SignUp화면에서 회원가입에 성공하면 회원이름, 이메일, uid가 database userInfo폴더에 저장되게 하였습니다. 주의)회원가입할때 이름 영어로 작성해야 데이터베이스에 저장됨

FEAT:Mypage xml 수정 및 Fragment생성

---

app/src/main/java/com/example/ccoli_market/DetailActivity.kt
app/src/main/java/com/example/ccoli_market/HomeFragment.kt

본인이 올린 글 확인 가능, 본인이 등록한 판매글이면 채팅버튼, 관심버튼 비활성화, 상세페이지 이동시 본인의 글이라는 ToastMessage 표시 HomeFragment.kt / DetailActivity.kt 수정

FEAT : 상세페이지 수정

---

.idea/misc.xml
app/src/main/java/com/example/ccoli_market/DetailActivity.kt
app/src/main/res/drawable/baseline_more_vert_24.xml
app/src/main/res/layout/activity_detail.xml

FEAT: 수정 메뉴바 생성

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/example/ccoli_market/AddItemActivity.kt
app/src/main/java/com/example/ccoli_market/ArticleModel.kt
app/src/main/java/com/example/ccoli_market/DetailActivity.kt
app/src/main/java/com/example/ccoli_market/EditItemActivity.kt
app/src/main/java/com/example/ccoli_market/HomeFragment.kt
app/src/main/res/layout/activity_edit_item.xml

등록된 게시글에 들어가 파이어베이스의 데이터를 수정&삭제하는 기능 생성
ArticleModel 에 articlemodelid -> 물품의 고유 ID 생성

FEAT: 게시글 수정하기 & 삭제하기

---

.idea/.name
.idea/misc.xml
app/src/main/java/com/example/ccoli_market/AddItemActivity.kt
app/src/main/java/com/example/ccoli_market/ArticleModel.kt
app/src/main/java/com/example/ccoli_market/DetailActivity.kt
app/src/main/java/com/example/ccoli_market/HomeFragment.kt
app/src/main/res/layout/activity_detail.xml
app/src/main/res/layout/activity_edit_item.xml
app/src/main/res/layout/product_list.xml

수정 레이아웃에 판매상태 라디오버튼 추가했고 디테일 레이아웃에 판매상태 부분 추가하였습니다. ArticleModel에 status라는 판매상태 데이터베이스 추가하였습니다. (처음 상품 등록할때 디폴트값: 판매중)

FEAT: 수정, 디테일 레이아웃 수정 및 판매상태 데이터베이스추가

---

app/src/main/java/com/example/ccoli_market/EditItemActivity.kt
app/src/main/res/layout/activity_edit_item.xml

올린글을 수정하는 Activity에 판매상태에 대한 정보를 수정하는 코드를 추가하였습니다.

FEAT: 올린글 수정 판매상태 추가

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/example/ccoli_market/DetailActivity.kt

DetailActivity 를 수정하여 사용자가 작성한 글에만 수정이 가능하도록 기능 추가

FEAT: 사용자가 작성한 글이 아니면 수정이 아닌 신고가능하게 수정

---

app/src/main/java/com/example/ccoli_market/DetailActivity.kt
app/src/main/java/com/example/ccoli_market/EditItemActivity.kt
app/src/main/java/com/example/ccoli_market/HomeFragment.kt

FEAT: 수정하기 누르면 리스트에서 바로 바뀌는 기능

---

.idea/.name
app/build.gradle
app/src/main/java/com/example/ccoli_market/EditItemActivity.kt
app/src/main/java/com/example/ccoli_market/SignUpActivity.kt

FEAT: 회원가입 데이터베이스 만듦

---

app/src/main/java/com/example/ccoli_market/AddItemActivity.kt
app/src/main/java/com/example/ccoli_market/ArticleModel.kt
app/src/main/java/com/example/ccoli_market/DetailActivity.kt
app/src/main/java/com/example/ccoli_market/HomeFragment.kt

detailInfo에 sellerId대신 게시물올린 userEmail뜨게 했습니다.
articleModel에 userEmail추가했습니다.

FEAT: detail화면 userEmail뜨게함

---

app/src/main/java/com/example/ccoli_market/ChattingRoomActivity.kt
app/src/main/java/com/example/ccoli_market/DetailActivity.kt
app/src/main/java/com/example/ccoli_market/EditItemActivity.kt
app/src/main/res/layout/activity_detail.xml
app/src/main/res/layout/activity_edit_item.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/fragment_home.xml
app/src/main/res/values-night/themes.xml
app/src/main/res/values/themes.xml

FEAT: 전체적인 코드 개선

---

.idea/misc.xml
app/src/main/java/com/example/ccoli_market/HomeFragment.kt
app/src/main/java/com/example/ccoli_market/MainActivity.kt

FEAT: 필터링 개선

---

app/src/main/java/com/example/ccoli_market/ChattingRoomActivity.kt
app/src/main/java/com/example/ccoli_market/HomeFragment.kt

Feat: 잠깐 주석처리

---

app/src/main/java/com/example/ccoli_market/HomeFragment.kt

FEAT: 필터링 기능 완성

---

app/src/main/java/com/example/ccoli_market/ChatFragment.kt
app/src/main/java/com/example/ccoli_market/ChatViewModel.kt
app/src/main/java/com/example/ccoli_market/ChattingRoomActivity.kt
app/src/main/java/com/example/ccoli_market/DetailActivity.kt
app/src/main/java/com/example/ccoli_market/recyclerview/ChattingRoomItem.kt
app/src/main/java/com/example/ccoli_market/recyclerview/ChattingRoomItemRecyclerViewAdapter.kt

FEAT: Chat 상품, 유저 마다 채팅방 구별

---

app/src/main/java/com/example/ccoli_market/SignUpActivity.kt

회원가입 내용 데이터베이스에 연동 users에 email,name,uid 순서로 저장

FEAT: 회원가입 데이터베이스 수정

---

app/src/main/java/com/example/ccoli_market/MessageActivity.kt
app/src/main/res/layout/activity_chatting_room.xml

FEAT : 채팅룸 백버튼 기능

---

app/src/main/java/com/example/ccoli_market/LoginActivity.kt
app/src/main/java/com/example/ccoli_market/MainActivity.kt
app/src/main/res/layout/item_chatting_room.xml
app/src/main/res/layout/item_message.xml

한번 로그인하면 로그아웃하기 전까지 로그인 안해도 됨 ㅎ

FEAT: 자동로그인

---

app/src/main/java/com/example/ccoli_market/HomeFragment.kt

검색필터 삭제 후 스피너에 "전체", "판매중", "판매완료" 만 나오도록 수정

FEAT : 필터링 [검색필터] 삭제
